apiVersion: v1
kind: Service
metadata:
  name: {{ template "databricks-specific-provisioner.name" . }}
  labels:
{{- include "databricks-specific-provisioner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "databricks-specific-provisioner.name" . }}
