apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: databricks-es
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: fake-databricks
    kind: ClusterSecretStore
  target:
    name: databricks-addons-secrets
  dataFrom:
    - extract:
        key: databricks-provisioner
