spring:
  application:
    name: databricks-specific-provisioner

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

azure:
  auth:
    clientId: ${AZURE_CLIENT_ID}
    tenantId: ${AZURE_TENANT_ID}
    clientSecret: ${AZURE_CLIENT_SECRET}
    skuType:  '' #allowed only PREMIUM or TRIAL. If different, premium will be set as default

  permissions:
    auth_clientId: ${PERMISSIONS_AZURE_CLIENT_ID}
    auth_tenantId: ${PERMISSIONS_AZURE_TENANT_ID}
    auth_clientSecret: ${PERMISSIONS_AZURE_CLIENT_SECRET}
    roleDefinitionId: ''
    subscriptionId: ${AZURE_SUBSCRIPTION_ID}
    resourceGroup: ${AZURE_RESOURCE_GROUP_NAME}

databricks:
  auth:
    accountId: ${DATABRICKS_ACCOUNT_ID}

git:
  username: ${GIT_USERNAME}
  token: ${GIT_TOKEN}
  provider: GITLAB

forkjoin:
  parallelism: 16


usecasetemplateid:
  workload:
    job: ["urn:dmb:utm:databricks-workload-job-template"]
    dlt: ["urn:dmb:utm:databricks-workload-dlt-template"]
